import streamlit as st
import json
# import sys
# st.write(sys.path)
st.header ("Photolithography", divider=True)
st.sidebar.markdown("# Photolithography")
st.subheader("Problem Overview",divider=True)
st.image("./src/figures/EUV_tool.png", caption="An ASML EUV Photolithography tool [https://www.cnbc.com/2022/03/23/inside-asml-the-company-advanced-chipmakers-use-for-euv-lithography.html]")
st.markdown("Photolithography is major process step (out of many) necessary for the construction of a semiconducting device (AKA a compute chip). In the pursuit of maintaining Moore's Law, the photolithography process has required Extreme UltraViolet (EUV) light to produce geometries at the nanometer-scale. Above, one can see inside one of ASML's EUV Photolithography tools. While these tools can achieve incredible precision, Intel and TSMC mainly use the exact same tools. What differentiates the two companies lies in their process control. Intel and TSMC still need to adjust the tool parameters to squeeze every last bit of performance out the equipment to maximize yield and throughput. Photolithography was one of the first process in semiconductor manufacturing in which wafer-to-wafer process control was applied. I will detail a fairly old version of this wafer-to-wafer process control below.")
st.subheader("Wafer-to-Wafer Process Control",divider=True)
st.image("./src/figures/Wafer_map.png",caption="Example of 300mm wafer with individual die shown")
st.markdown("On each wafer lie a number of die (or products), the number of which vary based on the product size. An example of a die layout on a wafer is shown above. For each die, the photolithography tool must expose a circuit pattern onto each die (termed _field_) and precisely overlay each pattern onto the previous circuit pattern. This distance between the target pattern location and the resulting pattern location is termed the _overlay error_. The sum of the overlay error across all layers of the product is termed the _stackup overlay error_. Both of these errors must be precisely controlled, else the device will not work.")
st.image("./src/figures/Overlay_Error_Notation.png",caption="Overlay error notation [Dr. Dragan Djurdjanovic (Time-Series Analysis)]")
st.markdown("There are two sets of coordinate systems: the _global coordinate system_ and the _local coordinate system_. To fully define the location of a marker on the wafer, one needs both the global coordinates $(X_i,Y_i)$ and the local coordinates $(x_i,y_i)$. The distance between the target marker and the realized marker in the $x$ and $y$ direction are termed $o_x(X_i,Y_i,x_i,y_i)$ and $o_y(X_i,Y_i,x_i,y_i)$, respectively. Utilizing the standard Zernike Polynomial model for photolithography (similar to https://doi.org/10.1115/1.4038074),")
st.latex("o_x(X_i,Y_i,x_i,y_i) = C_{x,X_{i}^{0} Y_{i}^{0}} + X_{i} C_{x,X_{i}^{1} Y_{i}^{0}} + Y_{i} C_{x,X_{i}^{0} Y_{i}^{1}} + X_{i}^{2} C_{x,X_{i}^{2} Y_{i}^{0}} + X_{i} Y_{i} C_{x,X_{i}^{1} Y_{i}^{1}} + Y_{i}^{2} C_{x,X_{i}^{0} Y_{i}^{2}} + X_{i}^{3} C_{x,X_{i}^{3} Y_{i}^{0}} + X_{i}^{2} Y_{i} C_{x,X_{i}^{2} Y_{i}^{1}} + X_{i} Y_{i}^{2} C_{x,X_{i}^{1} Y_{i}^{2}} + Y_{i}^{3} C_{x,X_{i}^{0} Y_{i}^{3}} + x_{i} C_{x, x_i^{1} y_i^{0}} + y_{i} C_{x, x_i^{0} y_i^{1}} + x_{i}^{2} C_{x, x_i^{2} y_i^{0}} + x_{i} y_{i} C_{x, x_i^{1} y_i^{1}} + y_{i}^{2} C_{x, x_i^{0} y_i^{2}} + x_{i}^{3} C_{x, x_i^{3} y_i^{0}} + x_{i}^{2} y_{i} C_{x, x_i^{2} y_i^{1}} + x_{i} y_{i}^{2} C_{x, x_i^{1} y_i^{2}} + y_{i}^{3} C_{x, x_i^{0} y_i^{3}} + r_x(X_i,Y_i,x_i,y_i) \\newline o_y(X_i,Y_i,x_i,y_i) = C_{y,X_{i}^{0} Y_{i}^{0}} + X_{i} C_{y,X_{i}^{1} Y_{i}^{0}} + Y_{i} C_{y,X_{i}^{0} Y_{i}^{1}} + X_{i}^{2} C_{y,X_{i}^{2} Y_{i}^{0}} + X_{i} Y_{i} C_{y,X_{i}^{1} Y_{i}^{1}} + Y_{i}^{2} C_{y,X_{i}^{0} Y_{i}^{2}} + X_{i}^{3} C_{y,X_{i}^{3} Y_{i}^{0}} + X_{i}^{2} Y_{i} C_{y,X_{i}^{2} Y_{i}^{1}} + X_{i} Y_{i}^{2} C_{y,X_{i}^{1} Y_{i}^{2}} + Y_{i}^{3} C_{y,X_{i}^{0} Y_{i}^{3}} + x_{i} C_{y, x_i^{1} y_i^{0}} + y_{i} C_{y, x_i^{0} y_i^{1}} + x_{i}^{2} C_{y, x_i^{2} y_i^{0}} + x_{i} y_{i} C_{y, x_i^{1} y_i^{1}} + y_{i}^{2} C_{y, x_i^{0} y_i^{2}} + x_{i}^{3} C_{y, x_i^{3} y_i^{0}} + x_{i}^{2} y_{i} C_{y, x_i^{2} y_i^{1}} + x_{i} y_{i}^{2} C_{y, x_i^{1} y_i^{2}} + y_{i}^{3} C_{y, x_i^{0} y_i^{3}} + r_y(X_i,Y_i,x_i,y_i)")

st.markdown("which can be placed into matrix form as")
st.latex("\\vec{o} = \\left[ \\begin{matrix} o_x(X_1,Y_1,x_1,y_1) \\newline o_y(X_1,Y_1,x_1,y_1) \\newline \\vdots \\newline o_y(X_{n_m},Y_{n_m},x_{n_m},y_{n_m}) \\end{matrix} \\right] = \\left[ \\begin{matrix} 1 && 0 && X_1 && 0 && Y_1 && 0 && X_1^{2} && 0 && X_1 Y_1 && 0 && Y_1^{2} && 0 && X_1^{3} && 0 && X_1^{2} Y_1 && 0 && X_1 Y_1^{2} && 0 && Y_1^{3} && 0 && x_1 && 0 && y_1 && 0 && x_1^{2} && 0 && x_1 y_1 && 0 && y_1^{2} && 0 && x_1^{3} && 0 && x_1^{2} y_1 && 0 && x_1 y_1^{2} && 0 && y_1^{3} && 0\\newline"
                                                                                                                                                                                                                  "0 && 1 && 0 && X_1 && 0 && Y_1 && 0 && X_1^{2} && 0 && X_1 Y_1 && 0 && Y_1^{2} && 0 && X_1^{3} && 0 && X_1^{2} Y_1 && 0 && X_1 Y_1^{2} && 0 && Y_1^{3} && 0 && x_1 && 0 && y_1 && 0 && x_1^{2} && 0 && x_1 y_1 && 0 && y_1^{2} && 0 && x_1^{3} && 0 && x_1^{2} y_1 && 0 && x_1 y_1^{2} && 0 && y_1^{3}\\newline"
                                                                                                                                                                                                                  " && && && && && && \\vdots \\newline"
                                                                                                                                                                                                                  "0 && 1 && 0 && X_{n_m} && 0 && Y_{n_m} && 0 && X_{n_m}^{2} && 0 && X_{n_m} Y_{n_m} && 0 && Y_{n_m}^{2} && 0 && X_{n_m}^{3} && 0 && X_{n_m}^{2} Y_{n_m} && 0 && X_{n_m} Y_{n_m}^{2} && 0 && Y_{n_m}^{3} && 0 && x_{n_m} && 0 && y_{n_m} && 0 && x_{n_m}^{2} && 0 && x_{n_m} y_{n_m} && 0 && y_{n_m}^{2} && 0 && x_{n_m}^{3} && 0 && x_{n_m}^{2} y_{n_m} && 0 && x_{n_m} y_{n_m}^{2} && 0 && y_{n_m}^{3}\\newline"
                                                                                                                                                                                                    "\\end{matrix} \\right] \\newline"
                                                                                                                                                                                                    "\\times \\left[ \\begin{matrix} C_{x,X_{i}^{0} Y_{i}^{0}} \\newline C_{y,X_{i}^{0} Y_{i}^{0}} \\newline  C_{x,X_{i}^{1} Y_{i}^{0}} \\newline C_{y,X_{i}^{1} Y_{i}^{0}} \\newline C_{x,X_{i}^{0} Y_{i}^{1}} \\newline C_{y,X_{i}^{0} Y_{i}^{1}} \\newline C_{x,X_{i}^{2} Y_{i}^{0}} \\newline C_{y,X_{i}^{2} Y_{i}^{0}} \\newline C_{x,X_{i}^{1} Y_{i}^{1}} \\newline C_{y,X_{i}^{1} Y_{i}^{1}} \\newline C_{x,X_{i}^{0} Y_{i}^{2}} \\newline C_{y,X_{i}^{0} Y_{i}^{2}} \\newline C_{x,X_{i}^{3} Y_{i}^{0}} \\newline C_{y,X_{i}^{3} Y_{i}^{0}} \\newline C_{x,X_{i}^{2} Y_{i}^{1}} \\newline C_{y,X_{i}^{2} Y_{i}^{1}} \\newline C_{x,X_{i}^{1} Y_{i}^{2}} \\newline C_{y,X_{i}^{1} Y_{i}^{2}} \\newline C_{x,X_{i}^{0} Y_{i}^{3}} \\newline C_{y,X_{i}^{0} Y_{i}^{3}} \\newline  C_{x,x_{i}^{1} y_{i}^{0}} \\newline C_{y,x_{i}^{1} y_{i}^{0}} \\newline C_{x,x_{i}^{0} y_{i}^{1}} \\newline C_{y,x_{i}^{0} y_{i}^{1}} \\newline C_{x,x_{i}^{2} y_{i}^{0}} \\newline C_{y,x_{i}^{2} y_{i}^{0}} \\newline C_{x,x_{i}^{1} y_{i}^{1}} \\newline C_{y,x_{i}^{1} y_{i}^{1}} \\newline C_{x,x_{i}^{0} y_{i}^{2}} \\newline C_{y,x_{i}^{0} y_{i}^{2}} \\newline C_{x,x_{i}^{3} y_{i}^{0}} \\newline C_{y,x_{i}^{3} y_{i}^{0}} \\newline C_{x,x_{i}^{2} y_{i}^{1}} \\newline C_{y,x_{i}^{2} y_{i}^{1}} \\newline C_{x,x_{i}^{1} y_{i}^{2}} \\newline C_{y,x_{i}^{1} y_{i}^{2}} \\newline C_{x,x_{i}^{0} y_{i}^{3}} \\newline C_{y,x_{i}^{0} y_{i}^{3}} \\newline \\end{matrix} \\right]")

st.markdown("Utilizing this model, we aim to model the bias terms and correct them, wafer-by-wafer. Ideally, with enough data, we would be able to utilize the full model below. This model considers the previous bias from the last field and the last wafer at the same field.")
st.latex("\\vec{o}_{i,j,k} \\sim \\text{overlay errors for wafer } i \\text{, layer } j \\text{, field } k")
st.latex("\\vec{\\chi}_{i,j,k} = A_1(\\vec{\\theta}) \\vec{\\chi}_{i,j-1,k} + A_2(\\vec{\\theta}) \\vec{\\chi}_{i,j,k-1} + \\vec{q}_{i,j,k} || \\vec{q}_{i,j,k} \\sim \\mathcal{N}(\\vec{0}, Q_{j,k}(\\vec{\\theta}))")
st.latex("\\vec{o}_{i,j,k} = \\vec{\\chi}_{i,j,k} + \\Phi_{i,j,k} \\vec{u}_{i,j,k} + \\vec{r}_{i,j,k} || \\vec{r}_{i,j,k} \\sim \\mathcal{N}(\\vec{0}, R_{j,k}(\\vec{\\theta}))")
st.markdown("However, I don't have access to that much data. So, I'll simplify the model.")
st.latex("\\vec{o}_{i} \\sim \\text{overlay errors for wafer } i")
st.latex("\\vec{\\chi}_{i} = A(\\vec{\\theta}) \\vec{\\chi}_{i-1} + \\vec{q}_{i} || \\vec{q}_{i} \\sim \\mathcal{N}(\\vec{0}, Q(\\vec{\\theta}))")
st.latex("\\vec{o}_{i} = \\vec{\\chi}_{i} + \\Phi \\vec{u}_{i} + \\vec{r}_{i} || \\vec{r}_{i} \\sim \\mathcal{N}(\\vec{0}, R(\\vec{\\theta}))")
st.markdown("We will assume that we have control over the inputs that will allow the following")
st.latex("\\Phi \\in \\mathbb{R}^{(2 \\text{x} n_m) \\text{x} 33} = \\left[ \\begin{matrix} 1 && 0 && X_1 && 0 && Y_1 && 0 && X_1^{2} && 0 && X_1 Y_1 && 0 && Y_1^{2} && 0 && X_1^{3} && 0 && X_1^{2} Y_1 && 0 && X_1 Y_1^{2} && 0 && Y_1^{3} && 0 && x_1 && 0 && y_1 && 0 && x_1^{2} && 0 && y_1^{2} && 0 && x_1^{3} && 0 && y_1^{3} && 0 && 0\\newline"
                                         "0 && 1 && 0 && X_1 && 0 && Y_1 && 0 && X_1^{2} && 0 && X_1 Y_1 && 0 && Y_1^{2} && 0 && X_1^{3} && 0 && X_1^{2} Y_1 && 0 && X_1 Y_1^{2} && 0 && Y_1^{3} && 0 && x_1 && 0 && y_1 && 0 && x_1^{2} && 0 && x_1 y_1 && 0 && y_1^{2} && 0 && x_1 y_1^{2} && y_1^{3}\\newline"
                                         " && && && && && && \\vdots \\newline"
                                         "0 && 1 && 0 && X_{n_m} && 0 && Y_{n_m} && 0 && X_{n_m}^{2} && 0 && X_{n_m} Y_{n_m} && 0 && Y_{n_m}^{2} && 0 && X_{n_m}^{3} && 0 && X_{n_m}^{2} Y_{n_m} && 0 && X_{n_m} Y_{n_m}^{2} && 0 && Y_{n_m}^{3} && 0 && x_{n_m} && 0 && y_{n_m} && 0 && x_{n_m}^{2} && 0 && x_{n_m} y_{n_m} && 0 && y_{n_m}^{2} && 0 && x_{n_m} y_{n_m}^{2} && y_{n_m}^{3}\\newline"
                                         "\\end{matrix} \\right]")
st.latex("\\vec{u}_i \\in \\mathbb{R}^{33 \\text{x} 1} = \\left[ \\begin{matrix} C_{x,X_i^{0} Y_i^{0}} \\newline  C_{y,X_i^{0} Y_i^{0}} \\newline C_{x,X_i^{1} Y_i^{0}} \\newline C_{y,X_i^{1} Y_i^{0}} \\newline C_{x,X_i^{0} Y_i^{1}} \\newline C_{y,X_i^{0} Y_i^{1}} \\newline C_{x,X_i^{2} Y_i^{0}} \\newline C_{y,X_i^{2} Y_i^{0}} \\newline C_{x,X_i^{1} Y_i^{1}} \\newline C_{y,X_i^{1} Y_i^{1}} \\newline C_{x,X_i^{0} Y_i^{2}} \\newline C_{y,X_i^{0} Y_i^{2}} \\newline C_{x,X_i^{3} Y_i^{0}} \\newline C_{y,X_i^{3} Y_i^{0}} \\newline C_{x,X_i^{2} Y_i^{1}} \\newline C_{y,X_i^{2} Y_i^{1}} \\newline C_{x,X_i^{1} Y_i^{2}} \\newline C_{y,X_i^{1} Y_i^{2}} \\newline C_{x,X_i^{0} Y_i^{3}} \\newline C_{y,X_i^{0} Y_i^{3}} \\newline C_{x,x_i^{1} y_i^{0}} \\newline C_{y,x_i^{1} y_i^{0}} \\newline C_{x,x_i^{0} y_i^{1}} \\newline C_{y,x_i^{0} y_i^{1}} \\newline C_{x,x_i^{2} y_i^{0}} \\newline C_{y,x_i^{2} y_i^{0}} \\newline C_{x,x_i^{0} y_i^{2}} \\newline C_{y,x_i^{1} y_i^{1}} \\newline C_{x,x_i^{3} y_i^{0}} \\newline C_{y,x_i^{0} y_i^{2}} \\newline C_{x,x_i^{0} y_i^{3}} \\newline C_{y,x_i^{1} y_i^{2}} \\newline C_{y,x_i^{0} y_i^{3}} \\newline \\end{matrix} \\right]")
